"""empty message

Revision ID: f844cbda356b
Revises:
Create Date: 2017-05-06 07:08:29.221142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f844cbda356b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('albums',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('isrc', sa.Text(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('artist_id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.Text(), nullable=True),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('isrc')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums')
    op.drop_table('artists')
    # ### end Alembic commands ###
